const money=n=>Math.round(n).toLocaleString('ko-KR')+'원';
const num=id=>Number(document.getElementById(id).value)||0;
function badge(el,type,text){el.className='result-badge '+type;el.textContent=text}
function calcProfit(){const p=num('profit-price'),c=num('profit-cost'),pack=num('profit-pack'),ship=num('profit-ship'),fee=(num('profit-platform')+num('profit-payment'))/100,ad=num('profit-ad')/100,ret=num('profit-return')/100,loss=num('profit-return-loss');const sales=p*(1-ret);const fees=p*(fee+ad);const profit=sales-c-pack-ship-fees-(ret*loss);const margin=p?profit/p*100:0;document.getElementById('profit-value').textContent=money(profit);document.getElementById('profit-margin').textContent=margin.toFixed(1)+'%';document.getElementById('profit-cost-rate').textContent=(c/p*100).toFixed(1)+'%';document.getElementById('profit-roas').textContent=(ad?1/ad:0).toFixed(2)+'배';const b=document.getElementById('profit-badge');if(margin>=25)badge(b,'good','수익 구조 양호');else if(margin>=10)badge(b,'warning','개선 필요');else badge(b,'danger','적자 위험');document.getElementById('profit-diagnosis').innerHTML='<span>진단</span><p>'+(margin>=25?'현재 구조는 광고 확대를 검토할 수 있습니다.':margin>=10?'원가·광고비·판매가 중 조정 가능한 항목을 확인하세요.':'가격 또는 비용 구조 개선이 우선입니다.')+'</p>';const rows=[['원가',c],['수수료·광고',fees],['배송·포장',ship],['순이익',profit]];document.getElementById('profit-breakdown').innerHTML=rows.map(x=>`<div class="breakdown-row ${x[0]=='순이익'?'profit':''}"><span>${x[0]}</span><div class="breakdown-track"><i style="width:${Math.min(Math.abs(x[1]/p*100),100)}%"></i></div><b>${money(x[1])}</b></div>`).join('')}
function calcPrice(){const c=num('price-cost')+num('price-extra'),rate=(num('price-fee')+num('price-ad'))/100,ret=num('price-return')/100,target=num('price-target');let price=c+target;price=price/(1-rate);price=price/(1-ret);price=Math.ceil(price/1000)*1000;document.getElementById('price-value').textContent=money(price);document.getElementById('price-profit').textContent=money(target);document.getElementById('price-margin').textContent=(target/price*100).toFixed(1)+'%';}
function calcBep(){const fixed=num('bep-fixed'),price=num('bep-price'),variable=num('bep-variable'),days=num('bep-days');const margin=price-variable;const units=margin>0?Math.ceil(fixed/margin):0;document.getElementById('bep-units').textContent=units.toLocaleString()+'개';document.getElementById('bep-sales').textContent=money(units*price);document.getElementById('bep-daily').textContent=(units/days).toFixed(1)+'개';}
function calcInventory(){const stock=num('inventory-stock')+num('inventory-incoming'),sales=num('inventory-sales'),lead=num('inventory-lead'),safe=num('inventory-safety'),target=num('inventory-target');const months=sales?stock/sales:0;const daily=sales/30;const rop=Math.ceil(daily*(lead*7)+safe);document.getElementById('inventory-months').textContent=months.toFixed(1)+'개월';document.getElementById('inventory-rop').textContent=rop+'개';document.getElementById('inventory-order').textContent=Math.max(rop-stock,0)+'개';const b=document.getElementById('inventory-badge');if(months>target*1.5)badge(b,'danger','과다 재고');else if(months>target)badge(b,'warning','주의');else badge(b,'good','적정')}
['profit-form','price-form','bep-form','inventory-form'].forEach(id=>document.getElementById(id).addEventListener('submit',e=>{e.preventDefault();({ 'profit-form':calcProfit,'price-form':calcPrice,'bep-form':calcBep,'inventory-form':calcInventory}[id])()}));document.querySelectorAll('input').forEach(i=>i.addEventListener('input',()=>{calcProfit();calcPrice();calcBep();calcInventory()}));
document.querySelectorAll('.copy-button').forEach(btn=>btn.onclick=()=>{const t=document.getElementById(btn.dataset.copyTarget).innerText;navigator.clipboard?.writeText(t);const toast=document.getElementById('toast');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)});
calcProfit();calcPrice();calcBep();calcInventory();